name: LegendQuests
version: '${version}'
main: xyz.raitaki.legendquests.LegendQuests
api-version: '1.20'
depend: [PlaceholderAPI]
commands:
  editquest:
    permission: legendquests.editquest
  createquest:
    permission: legendquests.createquest