questtracker:
  location:
    ==: org.bukkit.Location
    world: world
    x: 1
    y: 1
    z: 1
    pitch: 1
    yaw: 1
database: # ONLY MARIADB IS SUPPORTED
  host: localhost
  port: 3306
  database: database
  username: username
  password: password